add social media cards

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,6 +9,7 @@
 #                                  FEATURES                                       #
 # Updates the "updated" field in the front matter of .md files.                   #
 # Compresses PNG files with either oxipng or optipng if available.                #
+# Creates/updates the social media card for .md files.                            #
 # Runs subset_font if config.toml has been modified.                              #
 # Aborts the commit if a draft .md file or a file with "TODO" is being committed. #
 ###################################################################################
@@ -49,7 +50,7 @@ function has_body_changes() {
     local in_front_matter=1
     local triple_plus_count=0
 
-    diff_output=$(git diff --unified=999 --cached "$file")
+        diff_output=$(git diff --unified=999 --cached --output-indicator-new='%' --output-indicator-old='&' "$file")
 
     while read -r line; do
         if [[ "$line" =~ ^\+\+\+$ ]]; then
@@ -58,7 +59,7 @@ function has_body_changes() {
                 in_front_matter=0
             fi
         elif [[ $in_front_matter -eq 0 ]]; then
-            if [[ "$line" =~ ^[+-] ]]; then
+            if [[ "$line" =~ ^[\%\&] ]]; then
                 return 0
             fi
         fi
@@ -66,51 +67,26 @@ function has_body_changes() {
     return 1
 }
 
-# Check if oxipng is installed.
-png_compressor=""
-if command -v oxipng &> /dev/null; then
-    png_compressor="oxipng -o max"
-elif command -v optipng &> /dev/null; then
-    png_compressor="optipng -o 7"
-fi
+# Function to update the social media card for a post or section.
+function generate_and_commit_card {
+    local file=$1
+    social_media_card=$(social-cards-zola -o static/img/social_cards -b http://127.0.0.1:1025 -u -p -i "$file") || {
+        echo "Failed to update social media card for $file"
+        exit 1
+    }
+    
+    git add "$social_media_card" || {
+        echo "Failed to add social media card $social_media_card"
+        exit 1
+    }
+    
+    git add "$file" || {
+        echo "Failed to add $file"
+        exit 1
+    }
+}
 
-##################################################################
-# Compress PNG files with either oxipng or optipng if available. #
-# Update the "updated" field in the front matter of .md files.   #
-#          https://osc.garden/blog/zola-date-git-hook/           #
-# Interrupt the commit if a draft .md file is being committed.   #
-##################################################################
-
-# Get the newly added and modified files.
-all_changed_files=$(git diff --cached --name-only)
-# The command above gets all the files that have been added or modified, 
-
-# Loop through each newly added or modified .md or .png file for PNG optimization and draft checking.
-for file in $all_changed_files; do
-    # Ignore this script.
-    if [[ "$file" == "$0" ]]; then
-        continue
-    fi
-
-    # If the file is a PNG and png_compressor is set, compress it and add it to the commit.
-    if [[ "$file" == *.png ]] && [[ -n "$png_compressor" ]]; then
-        $png_compressor "$file" || error_exit "Failed to compress PNG file $file"
-        git add --force "$file" || error_exit "Failed to add compressed PNG file $file"
-        continue
-    fi
-
-    # If the file is an .md file and it's a draft, abort the commit.
-    if [[ "$file" == *.md ]]; then
-        if is_draft "$file"; then
-            error_exit "Draft file $file is being committed!"
-        fi
-    fi
-
-    # If the file contains "TODO", abort the commit (unless it's this script).
-    if contains_todo "$file"; then
-        error_exit "File $file contains TODO! Remove or complete the TODO before committing."
-    fi
-done
+export -f generate_and_commit_card
 
 # Get the modified .md to update the "updated" field in the front matter.
 modified_files=$(git diff --cached --name-only --diff-filter=M | grep -E '\.md$' | grep -v '_index.md$')
@@ -153,6 +129,61 @@ for file in $modified_files; do
     # Stage the changes.
     git add "$file"
 done
+
+# Check if oxipng is installed.
+png_compressor=""
+if command -v oxipng &> /dev/null; then
+    png_compressor="oxipng -o max"
+elif command -v optipng &> /dev/null; then
+    png_compressor="optipng -o 7"
+fi
+
+##################################################################
+# Compress PNG files with either oxipng or optipng if available. #
+# Update the "updated" field in the front matter of .md files.   #
+#          https://osc.garden/blog/zola-date-git-hook/           #
+# Interrupt the commit if a draft .md file is being committed.   #
+# Interrupt the commit if a file with "TODO" is being committed. #
+# Create/update the social media card for posts and sections.    #
+# For more info about the social media cards part, see:          #
+#   https://osc.garden/blog/automating-social-media-cards-zola   #
+##################################################################
+
+# Get the newly added and modified files.
+all_changed_files=$(git diff --cached --name-only)
+
+# Loop through each newly added or modified .md or .png file for PNG optimization and draft checking.
+for file in $all_changed_files; do
+    # Ignore this script.
+    if [[ "$file" == "$0" ]]; then
+        continue
+    fi
+
+    # If the file is a PNG and png_compressor is set, compress it and add it to the commit.
+    if [[ "$file" == *.png ]] && [[ -n "$png_compressor" ]]; then
+        $png_compressor "$file" || error_exit "Failed to compress PNG file $file"
+        git add "$file" || error_exit "Failed to add compressed PNG file $file"
+        continue
+    fi
+
+    # If the file contains "TODO", abort the commit (unless it's this script).
+    if contains_todo "$file"; then
+        error_exit "File $file contains TODO! Remove or complete the TODO before committing."
+    fi
+
+    # If the file is an .md file and it's a draft, abort the commit.
+    if [[ "$file" == *.md ]]; then
+        if is_draft "$file"; then
+            error_exit "Draft file $file is being committed!"
+        fi
+    fi
+done
+
+# Use `social-cards-zola` to create/update the social media card for Markdown files.
+# See https://osc.garden/blog/automating-social-media-cards-zola/ for context.
+changed_md_files=$(echo "$all_changed_files" | grep '\.md$')
+# Use parallel to create the social media cards in parallel and commit them.
+echo "$changed_md_files" | parallel -j 8 generate_and_commit_card
 
 #########################################################
 # Run subset_font if config.toml has been modified.     #
